version: "3"

services:
  app:
    container_name: hanako
    build: .
    ports:
      - ${PORT}:${PORT}
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - hanako-postgres
    networks:
      - hanako

  hanako-postgres:
    image: postgres:latest
    container_name: db_postgres_hanako
    environment:
      - POSTGRES_USER=${db_user}
      - POSTGRES_PASSWORD=${db_pass}
      - POSTGRES_DB=${db_name}
      - DATABASE_HOST=${db_host}
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - hanako

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container_hanako
    environment:
      PGADMIN_DEFAULT_EMAIL : ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - hanako-postgres
    ports:
      - '5050:80'
    networks:
      - hanako
    restart: unless-stopped

  hanako-mongodb:
    image: mongo
    container_name: mongo_hanako
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
    networks:
      - hanako

volumes:
  api:
  database_postgres:
  mongodata:

networks:
  hanako:
    driver: bridge

