version: '3.7'

services:
  hanako-jaeger:
    image: jaegertracing/all-in-one:1.17.1
    container_name: hanako-jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9441
    ports:
    - '5775:5775/udp'
    - '5778:5778/udp'
    - '6831:6831/udp'
    - '6832:6832/udp'
    - '16686:16686'
    - '14268:14286'
